### ISSUE TITLE
About pointnext-s-c64-enc-dec-sameshape.pt

### ISSUE THREAD

**Issue by TeleeMa** [vlc-robot/polarnet#1]
Hi,

Thank you for your great work! When I ran the code, I met the problem of missing pointnext-s-c64-enc-dec-sameshape.pt. So is this pre-trained weight from original PointNext or from your fine-tuning?

By the way, I think in this line of config, https://github.com/vlc-robot/polarnet/blob/a8f6c624a9f0aad35d602a637253fd48ac267f57/polarnet/config/10tasks.yaml#L58
it should be 10_tasks_var.csv as 10tasks_var.csv does not exist in asset folder.

**Comment by TeleeMa** [comment]
Hi @rjgpinel,

Thank you for your reply! Very nice work!

**Comment by TeleeMa** [comment]
Sorry for reopening, I just found that the code uses 1 GPU with DDP, but mutiple GPUs with DP (https://github.com/vlc-robot/polarnet/blob/1f951a4addb47411e32c88de16d8fe1925f7e6f9/polarnet/utils/misc.py#L56). 

Are there any reasons for the setting?  Will the DDP influence the training using multiple GPUs?

**Comment by rjgpinel** [comment]
Hi @TeleeMa,

Let me try to explain what's going on on this part of the code:

For DDP training, we will start many processes where each process uses one GPU and has a unique rank id (or local rank id in the node). So for each process, there is just one GPU with local rank >= 0. 

If the local rank is not set, then it will use one process. If there are multiple GPUs in that process, it will use DataParallel to train.

I hope that's clear.

**Comment by rjgpinel** [comment]
Please, if you have an issue that's unrelated to this issue title "About pointnext-s-c64-enc-dec-sameshape.pt", open a new issue instead of reopening the same issue. 

This will help others to find more easily the same issue and faster for me to identify new issues. 
Thank you!

Closing this issue as solved.
