### ISSUE TITLE
Mismatched instr_embed_size.

### ISSUE THREAD

**Issue by turn0the0table** [vlc-robot/polarnet#5]
During the reproduction of the paper, I noticed that the instr_embed_size in the training_config of the trained model you provided is set to 1280, whereas PolarNet uses CLIP to generate an instr_embed_size of 512. It seems that the results cannot be directly evaluated. Should further data processing be performed?

**Comment by rgpinel** [comment]
Hi,

I am not sure what do you mean by  instr_embed_size being set to 1280. Where is this set in the config file?

I can see that the config file (https://drive.google.com/file/d/1L4kiTEDpcXCYTfRp3ol6XDNvybyQh3jh/view?usp=sharing) L99  is instr_embed_size: 512.
